// Generated by the WebObjects Assistant Mon Feb 24 01:28:40 US/Central 2003

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;

public class Main extends WOComponent {

    /** @TypeInfo KnowTestBank */
    protected EOEnterpriseObject knowtestbank;
    // This WODisplayGroup is initialized from the .woo archive in the component's constructor method
    protected WODisplayGroup knowtestbankDisplayGroup;

    public Main(WOContext context) {
        super(context);
    }


    public QuestionPage selectTestBank()
    {
        knowtestbankDisplayGroup.selectObject(knowtestbank);

        QuestionPage nextPage = (QuestionPage)pageWithName("QuestionPage");

        nextPage.knowTestQuestionsDisplayGroup.setMasterObject(knowtestbank);

        return nextPage;
    }
    
}
