// Generated by the WebObjects Assistant Mon Feb 24 01:35:39 US/Central 2003

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;

public class QuestionPage extends WOComponent {

    // This WODisplayGroup is initialized from the .woo archive in the component's constructor method
    protected WODisplayGroup knowTestQuestionsDisplayGroup;

    public QuestionPage(WOContext context) {
        super(context);
    }

}
