// Generated by the WebObjects Assistant Fri Feb 28 17:27:20 US/Central 2003

import com.webobjects.foundation.*;
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eoaccess.*;

public class TestListPage extends WOComponent {

    /** @TypeInfo KnowTest */
    protected EOEnterpriseObject knowtest;
    // This WODisplayGroup is initialized from the .woo archive in the component's constructor method
    protected WODisplayGroup knowtestDisplayGroup;

    public TestListPage(WOContext context) {
        super(context);
    }


}
